on:
  push: 
    branches: 
      - master
  schedule:
    - cron:  '* * * * *'

jobs:
  run:
    name: run
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run
        run: go run ./main.go
        env:
          PREFIX: ${{ env.PREFIX }}
          CONSUMER_KEY: ${{ env.CONSUMER_KEY }}
          CONSUMER_SECRET : ${{ env.CONSUMER_SECRET }}
          TOKEN : ${{ env.TOKEN }}
          TOKEN_SECRET: ${{ env.TOKEN_SECRET }}

